### ISSUE TITLE
Using hardcoded openldap version makes impossible an update for OpenLDAP 2.5

### ISSUE THREAD

**Issue by droideck** [sudo-project/sudo#105]
In the project's code, we have a hardcoded value:
https://github.com/sudo-project/sudo/blob/b0a32fe738af5c20594e2f8320e72f64a83f63c9/etc/sudo.pp#L349

We should use a library without a version so it becomes possible to update to the newest OpenLDAP version (2.5.X).

Steps to reproduce:
1. Download openldap 2.5:
https://koji.fedoraproject.org/koji/taskinfo?taskID=70077129 (it is a scratch build and it'll be removed in the future or I may improve it. Please, contact me for the newer version: spichugi@redhat.com) 
2. sudo dnf install openldap-2.5.5-1compat.fc35.x86_64.rpm  openldap-devel-2.5.5-1compat.fc35.x86_64.rpm 

Expected results:
- The package is successfully updated.

Actual results:
```
...
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, groups-manager, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
DNF version: 4.7.0
Command: dnf install openldap-2.5.5-1compat.fc35.x86_64.rpm openldap-devel-2.5.5-1compat.fc35.x86_64.rpm -d 10 
Installroot: /
Releasever: rawhide
cachedir: /var/cache/dnf
Base command: install
Extra commands: ['install', 'openldap-2.5.5-1compat.fc35.x86_64.rpm', 'openldap-devel-2.5.5-1compat.fc35.x86_64.rpm', '-d', '10']
User-Agent: constructed: 'libdnf (Fedora 35; generic; Linux.x86_64)'
repo: using cache for: beaker-Fedora
beaker-Fedora: using metadata from Sun 13 Jun 2021 10:06:11 AM CEST.
repo: using cache for: beaker-Fedora-Everything
beaker-Fedora-Everything: using metadata from Sun 13 Jun 2021 10:06:11 AM CEST.
repo: using cache for: beaker-harness
beaker-harness: using metadata from Mon 19 Apr 2021 04:35:10 PM CEST.
repo: using cache for: beaker-tasks
beaker-tasks: using metadata from Mon 14 Jun 2021 11:12:30 AM CEST.
repo: using cache for: fedora-cisco-openh264
fedora-cisco-openh264: using metadata from Tue 23 Feb 2021 01:47:28 AM CET.
repo: using cache for: rawhide
rawhide: using metadata from Sun 13 Jun 2021 10:06:11 AM CEST.
repo: using cache for: rawhide-modular
rawhide-modular: using metadata from Sun 13 Jun 2021 09:54:23 AM CEST.
Last metadata expiration check: 3:14:41 ago on Mon 14 Jun 2021 12:40:10 PM CEST.
timer: sack setup: 3941 ms
--> Starting dependency resolution
--> Finished dependency resolution
timer: depsolve: 1175 ms

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dnf/cli/main.py", line 130, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python3.10/site-packages/dnf/cli/main.py", line 166, in resolving
    base.resolve(cli.demands.allow_erasing)
  File "/usr/lib/python3.10/site-packages/dnf/base.py", line 860, in resolve
    raise exc
dnf.exceptions.DepsolveError: 
 Problem: The operation would result in removing the following protected packages: sudo
```

**Comment by millert** [comment]
That line in sudo.pp is specific to Debian packaging so is not relevant to your problem.

The actual issue is that on Fedora the LDAP library sudo links with is libldap-2.4.so.2 and you appear to be replacing that with else (perhaps something like libdlap-2.5.so.1).  This will prevent anything linked with libldap-2.4.so.2 to fail.  Sudo actually links with -lldap (no version) but since libldap.so is a link to libldap-2.4.so.2 the linker records libldap-2.4.so.2 for the dependency.  The rpm package just picks up the dependency from the shared libraries that are used.

I don't think sudo is doing anything wrong here.
